services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - src_volume:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  php:
    build: .
    volumes:
      - src_volume:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: awesomerootpassword
      MYSQL_DATABASE: avid
      MYSQL_USER: avid
      MYSQL_PASSWORD: avidawesomepassword
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password



volumes:
  src_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/src
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/db_data
  certbot-etc:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/certbot/conf
  certbot-www:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/certbot/www
